name: ip4rs
channels:
  # PyTorch channel *must* be the first channel otherwise CPU from conda-forge is used
  - pytorch
  - conda-forge
  - nodefaults
dependencies:
  # Use oldest python version according to NEP-29
  - python=3.8
  - numpy>=1.22
  - sentinelsat=1
  - jupyter=1
  - notebook
  - pydantic=1
  - dynaconf
  # updating geopandas or rasterio should
  # be done deliberately and tested!
  - matplotlib
  - geopandas=0.10
  - rasterio=1.2
  - osmnx
  - seaborn
  - easydict
  - scikit-learn
  - spectral
  - pytorch
  - torchvision
  - torchaudio
  - torchinfo
  - visdom
  - openpyxl
  - ipywidgets
  - jupyterlab_widgets
  # install cuda also for CPU only to keep the CPU/GPU version identical
  # this "only" results in larger files
  - cudatoolkit=10.2
  # for development
  - jupyterlab
  - black
  - isort
  - flake8
  - pytest
  - pre-commit
  - pip
  # implicit deps for simple_downloader
  - requests
  - rich
  - tqdm
  - pip:
    - "simple_downloader>=0.1.2"
